const students = [
    {
        id: 1,
        name: "Ahmed Hossam",
        phone: "01234567890",
        email: "ahmed@gmail.com",
        dateOfBirth: "2 / 1 / 2000",
        track: "open source",
        gender: "male",
        hobbies: ["football", "TV Show"],
        address: {
            location: "Cairo",
            Country: "Egypt",
            zipCode: 1220,
        },
    },
    {
        id: 2,
        name: "Omar Sayed",
        phone: "0112345678",
        email: "omar@gmail.com",
        dateOfBirth: "7/11/1998",
        track: "open source",
        gender: "male",
        hobbies: ["football", "TV Show"],
        address: {
            location: "Cairo",
            Country: "Egypt",
            zipCode: 1220,
        },
    },
    {
        id: 3,
        name: "Nouran Tarek",
        phone: "0112345678",
        email: "nour@gmail.com",
        dateOfBirth: "10/6/2001",
        track: "open source",
        gender: "female",
        hobbies: ["football", "TV Show"],
        address: {
            location: "Cairo",
            Country: "Egypt",
            zipCode: 1220,
        },
    },
    {
        id: 4,
        name: "Seif Osama",
        phone: "0102345678",
        email: "seif@gmail.com",
        dateOfBirth: "11/4/1999",
        track: "open source",
        gender: "male",
        hobbies: ["football", "TV Show"],
        address: {
            location: "Cairo",
            Country: "Egypt",
            zipCode: 1220,
        },
    },
    {
        id: 5,
        name: "New Student 1",
        phone: "0123456789",
        email: "newstudent1@gmail.com",
        dateOfBirth: "5/20/2002",
        track: "web development",
        gender: "female",
        hobbies: ["reading", "coding"],
        address: {
            location: "City X",
            Country: "Country Y",
            zipCode: 5678,
        },
    },
    {
        id: 6,
        name: "New Student 2",
        phone: "0111222333",
        email: "newstudent2@gmail.com",
        dateOfBirth: "8/15/2000",
        track: "data science",
        gender: "male",
        hobbies: ["music", "traveling"],
        address: {
            location: "City Z",
            Country: "Country W",
            zipCode: 9876,
        },
    },
    // Add more entries
    {
        id: 7,
        name: "Jane Doe",
        phone: "0123456789",
        email: "jane@gmail.com",
        dateOfBirth: "3/25/1995",
        track: "software engineering",
        gender: "female",
        hobbies: ["reading", "gaming"],
        address: {
            location: "City A",
            Country: "Country B",
            zipCode: 4567,
        },
    },
    {
        id: 8,
        name: "John Smith",
        phone: "0111111111",
        email: "john@gmail.com",
        dateOfBirth: "6/10/1998",
        track: "machine learning",
        gender: "male",
        hobbies: ["coding", "hiking"],
        address: {
            location: "City C",
            Country: "Country D",
            zipCode: 7890,
        },
    },
    {
        id: 9,
        name: "Sara Johnson",
        phone: "0101010101",
        email: "sara@gmail.com",
        dateOfBirth: "9/5/2001",
        track: "cybersecurity",
        gender: "female",
        hobbies: ["cybersecurity", "painting"],
        address: {
            location: "City E",
            Country: "Country F",
            zipCode: 2345,
        },
    },
    {
        id: 10,
        name: "Alex Rodriguez",
        phone: "0112233445",
        email: "alex@gmail.com",
        dateOfBirth: "12/12/1997",
        track: "front-end development",
        gender: "male",
        hobbies: ["music", "photography"],
        address: {
            location: "City G",
            Country: "Country H",
            zipCode: 7891,
        },
    },
];

  export default students;